spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  logging.level:
    org.hibernate.SQL: debug


  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

server:
  servlet:
    encoding:
      force-response: true